"""Added Vehicle Type to Item Table

Revision ID: 4e327f327ae7
Revises: 327ea5ddb124
Create Date: 2025-05-05 20:09:34.595673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e327f327ae7'
down_revision = '327ea5ddb124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
